apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sf-dialogmote
  namespace: team-dialog
  labels:
    team: team-dialog
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /isAlive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      cpu: 1000m
      memory: 4096Mi
    requests:
      cpu: 100m
      memory: 2048Mi
  accessPolicy:
    outbound:
      external:
        - host: login.salesforce.com
        - host: navdialog.my.salesforce.com
  envFrom:
    - secret: sf-dialogmote
  filesFrom:
    - secret: sf-dialogmote
  kafka:
    pool: nav-prod # enum of nav-dev, nav-prod
  env:
    - name: POSTER_SETTINGS # DEFAULT, FROM_BEGINNING, NO_POST, SAMPLE, RUN_ONCE, ENCODE_KEY, AVRO_VALUE, BYTES_AVRO_VALUE
      value: ENCODE_KEY, AVRO_VALUE
    - name: KAFKA_CLIENTID
      value: sf-dialogmote-v1
    - name: KAFKA_SECURITY
      value: 'TRUE'
    - name: KAFKA_SECPROT
      value: SASL_SSL
    - name: KAFKA_SASLMEC
      value: PLAIN
    - name: KAFKA_TOPIC
      value: teamsykefravr.isdialogmote-dialogmote-statusendring
    - name: MS_BETWEEN_WORK
      value: '600000'
    - name: SF_INSTANCE
      value: PRODUCTION
    - name: SF_TOKENHOST
      value: 'https://login.salesforce.com'
    - name: SF_VERSION
      value: 'v48.0'
    - name: VAULT_INSTANCE
      value: GCP
    - name: DEPLOY_APP
      value: {{ DEPLOY_APP }}