apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: kafka-dialog
  namespace: team-dialog
  labels:
    team: team-dialog
spec:
  webproxy: true
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /isAlive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi
  kafka:
    pool: nav-dev # enum of nav-dev, nav-prod
  env:
    - name: KAFKA_CLIENTID
      value: sf-stilling
    - name: KAFKA_SECURITY
      value: 'TRUE'
    - name: KAFKA_TOPIC
      value: 'teampam.stilling-ekstern-1'
    - name: MS_BETWEEN_WORK
      value: '2400000'
    - name: SF_INSTANCE
      value: PREPROD
    - name: SF_TOKENHOST
      value: 'https://test.salesforce.com'
    - name: SF_VERSION
      value: 'v48.0'
    - name: VAULT_INSTANCE
      value: PREPROD