spec:
  env:
    - name: KAFKA_TOPIC
      value: arbeidsgiver.sykefravarsstatistikk-naring-v1
    - name: KAFKA_CLIENT_ID
      value: sf-sykefravarsstatistikk-naring-v1
    - name: ENCODE_KEY
      value: 'true'