apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{ DEPLOY_APP }}
  namespace: team-dialog
  labels:
    team: team-dialog
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /isAlive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      cpu: 1000m
      memory: 4096Mi
    requests:
      cpu: 100m
      memory: 2048Mi
  accessPolicy:
    outbound:
      external:
        - host: test.salesforce.com
        - host: navdialog--preprod.my.salesforce.com
        - host: navdialog--uat.my.salesforce.com
  envFrom:
    - secret: sf-ia-sak
  filesFrom:
    - secret: sf-ia-sak
  kafka:
    pool: nav-dev # enum of nav-dev, nav-prod
  env:
    - name: POSTER_SETTINGS # DEFAULT, FROM_BEGINNING, NO_POST, SAMPLE, RUN_ONCE, ENCODE_KEY, AVRO_KEY_VALUE, AVRO_VALUE
      value: RUN_ONCE, SAMPLE
    - name: KAFKA_POLL_DURATION
      value: '10000'
    - name: KAFKA_CLIENTID
      value: crm-kafka-activity-oppgaver
    - name: KAFKA_TOPIC
      value: team-dialog.crm-kafka-activity-oppgaver
    - name: MS_BETWEEN_WORK
      value: '600000'
    - name: SF_TOKENHOST
      value: https://test.salesforce.com
    - name: DEPLOY_APP
      value: {{ DEPLOY_APP }}
    - name: DEPLOY_CLUSTER
      value: {{ DEPLOY_CLUSTER }}