/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.nav.pam.stilling.ext.avro;
@org.apache.avro.specific.AvroGenerated
public enum AdStatus implements org.apache.avro.generic.GenericEnumSymbol<AdStatus> {
  ACTIVE, INACTIVE, STOPPED, DELETED, REJECTED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AdStatus\",\"namespace\":\"no.nav.pam.stilling.ext.avro\",\"symbols\":[\"ACTIVE\",\"INACTIVE\",\"STOPPED\",\"DELETED\",\"REJECTED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
