/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package no.nav.pam.stilling.ext.avro;
@org.apache.avro.specific.AvroGenerated
public enum PrivacyChannel implements org.apache.avro.generic.GenericEnumSymbol<PrivacyChannel> {
  INTERNAL_NOT_SHOWN, SHOW_ALL, DONT_SHOW_EMPLOYER, DONT_SHOW_AUTHOR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PrivacyChannel\",\"namespace\":\"no.nav.pam.stilling.ext.avro\",\"symbols\":[\"INTERNAL_NOT_SHOWN\",\"SHOW_ALL\",\"DONT_SHOW_EMPLOYER\",\"DONT_SHOW_AUTHOR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
