spec:
  env:
    - name: KAFKA_TOPIC
      value: pia.sykefravarsstatistikk-naringskode-v1
    - name: KAFKA_CLIENT_ID
      value: sf-sykefravarsstatistikk-naringskode-v1
    - name: ENCODE_KEY
      value: 'true'