apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{ DEPLOY_APP }}
  namespace: team-dialog
  labels:
    team: team-dialog
spec:
  webproxy: true
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /isAlive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi
  accessPolicy:
    outbound:
      external:
        - host: login.salesforce.com
        - host: navdialog.my.salesforce.com
  envFrom:
    - secret: sf-permiteringsvarsel
  filesFrom:
    - secret: sf-permiteringsvarsel
  kafka:
    pool: nav-prod
  env:
    - name: POSTER_SETTINGS # DEFAULT, FROM_BEGINNING, NO_POST, SAMPLE, RUN_ONCE, ENCODE_KEY, AVRO_KEY_VALUE, AVRO_VALUE
      value: SAMPLE
    - name: KAFKA_POLL_DURATION
      value: '10000'
    - name: KAFKA_CLIENTID
      value: sf-permiteringsvarsel
    - name: KAFKA_TOPIC
      value: permittering-og-nedbemanning.aapen-permittering-arbeidsgiver
    - name: MS_BETWEEN_WORK
      value: '240000'
    - name: SF_TOKENHOST
      value: https://login.salesforce.com
    - name: SF_VERSION
      value: 'v48.0'
    - name: DEPLOY_APP
      value: {{ DEPLOY_APP }}
