name: Configure and run workflow

on: [push, pull_request]

jobs:
  build-deploy:
    uses: ./.github/workflows/workflow.yml
    secrets: inherit
    with:
      DEPLOY_APP: sf-crm-activity-tmp
      DEPLOY_CLUSTER: dev-gcp