name: Configure and run workflow

on: [push, pull_request]

jobs:
  call-main-workflow:
    uses: ./.github/workflows/workflow.yml
    with:
      DEPLOY_APP: sf-arbeidsgiver-kontaktskjema
      DEPLOY_CLUSTER: dev-gcp