name: Configure and run workflows

on: [push, pull_request]

jobs:
  build-push:
    uses: ./.github/workflows/build-push.yml
    permissions:
      contents: write
      id-token: write
    secrets: inherit
  setup-matrix: # enable running deploy for .nais/*/ in parallel
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set Matrix
        id: set-matrix
        run: |
          shopt -s nullglob
          appdirs=(.nais/*/)
          apps=("${appdirs[@]%/}")
          apps=("${apps[@]#.nais/}")
          declare -a appcluster
          i=0
          for app in "${apps[@]}"; do
            devcluster= prodcluster=
            for cluster in .nais/"$app"/*.yaml; do
              cluster=${cluster##*/}
              cluster=${cluster%.yaml}
              case $cluster in
                dev-*) devcluster=$cluster ;;
                prod-*) prodcluster=$cluster ;;
                *) printf 'Unknown cluster encountered: %s\n' "$cluster" >&2; exit 1
              esac
            done
            printf -v "appcluster[$((i++))]" '{"name":"%s","dev-cluster":"%s","prod-cluster":"%s"}' \
              "$app" "$devcluster" "$prodcluster"
          done
          json=$(jq -c -n '{app: $ARGS.positional}' --jsonargs "${appcluster[@]}")
          echo "::set-output name=matrix::$json"
  deploy-dev: # run on branches _other_ than main
    if: github.event_name != 'pull_request' && github.ref != 'refs/heads/main'
    needs:
      - setup-matrix
      - build-push
    strategy:
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    uses: ./.github/workflows/deploy.yml
    permissions:
      contents: write
      id-token: write
    secrets: inherit
    with:
      DEPLOY_APP: ${{ matrix.app.name }}
      DEPLOY_CLUSTER: ${{ matrix.app.dev-cluster }}
      IMAGE: ${{ needs.build-push.outputs.image }}
  deploy-prod: # run only on main
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
    needs:
      - setup-matrix
      - build-push
    strategy:
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    uses: ./.github/workflows/deploy.yml
    permissions:
      contents: write
      id-token: write
    secrets: inherit
    with:
      DEPLOY_APP: ${{ matrix.app.name }}
      DEPLOY_CLUSTER: ${{ matrix.app.prod-cluster }}
      IMAGE: ${{ needs.build-push.outputs.image }}
