name: Configure and run workflow

on: [push, pull_request]

jobs:
  build-deploy:
    uses: ./.github/workflows/workflow.yml
    permissions:
      contents: write
      id-token: write
    secrets: inherit
    with:
      DEPLOY_APP: sf-sykefravarsstatistikk-bransje
      DEPLOY_CLUSTER: prod-gcp
